import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

import { COPY } from '../content/copy.ts';
import { FACTS } from '../content/facts.ts';
import { routing } from '../src/i18n/routing.ts';

/**
 * Generates messages/<locale>.json from content/copy.ts.
 *
 * content/copy.ts stays the English source of truth — it is where copy gets
 * written and reviewed, with its rationale in comments beside it. This script
 * projects it into the flat-file format next-intl loads, and derives the other
 * locales as MARKED UNTRANSLATED strings.
 *
 * WHY THE PLACEHOLDERS KEEP THE ENGLISH TEXT. A placeholder of "TODO" would
 * make every Arabic page collapse to nothing, and the one thing that has to be
 * reviewable before a translator is booked is whether the RTL layout actually
 * works at real string lengths. `[[AR]] Request a pilot` mirrors correctly and
 * is impossible to mistake for a translation. `scripts/check-i18n.ts` fails a
 * production build while any marker remains, so it cannot ship.
 *
 * NOTHING HERE IS MACHINE TRANSLATED, and nothing in this script is capable of
 * translating. Arabic and Romanian copy is written by people who speak them.
 *
 * Run: npm run build:messages
 */

/**
 * Keys whose values are NOT copy: routes and the legal marker.
 * Translating a href breaks navigation.
 */
const NON_TRANSLATABLE_KEYS = new Set(['href', 'marker', 'privacyHref']);

/**
 * Every fact id, checked structurally rather than by the key that holds it.
 *
 * An earlier version of this script excluded fact ids by key name — factId,
 * factIds, ids, specs — and missed `investorsPublic.market.figures`, which is
 * also a list of fact ids. The result was FACTS['[[RO]] egypt-annual-pet-
 * consumption'], undefined, and a crash on /ro/investors and /ar/investors that
 * only surfaced when those routes started prerendering. Matching the value
 * against the real fact table cannot miss a key nobody thought of.
 */
const FACT_IDS = new Set(Object.keys(FACTS));

/** A path is a route, not a sentence. */
function isRoute(value: string): boolean {
  return value.startsWith('/') || value.startsWith('http');
}

type Node = string | number | boolean | Node[] | { [key: string]: Node };

const outstanding: { locale: string; path: string; english: string }[] = [];

function transform(node: Node, locale: string, path: string[], key?: string): Node {
  if (Array.isArray(node)) {
    return node.map((item, index) => transform(item, locale, [...path, String(index)], key));
  }

  if (node !== null && typeof node === 'object') {
    const out: { [key: string]: Node } = {};
    for (const [childKey, value] of Object.entries(node)) {
      out[childKey] = transform(value as Node, locale, [...path, childKey], childKey);
    }
    return out;
  }

  if (typeof node !== 'string') return node;
  if (key && NON_TRANSLATABLE_KEYS.has(key)) return node;
  if (isRoute(node)) return node;
  if (FACT_IDS.has(node)) return node;
  if (locale === routing.defaultLocale) return node;

  outstanding.push({ locale, path: path.join('.'), english: node });
  return `[[${locale.toUpperCase()}]] ${node}`;
}

const outputDir = join(process.cwd(), 'messages');
mkdirSync(outputDir, { recursive: true });

for (const locale of routing.locales) {
  const messages = transform(COPY as unknown as Node, locale, []);
  writeFileSync(
    join(outputDir, `${locale}.json`),
    `${JSON.stringify(messages, null, 2)}\n`,
    'utf8',
  );
}

// ---------------------------------------------------------------------------
// The translator's worklist
// ---------------------------------------------------------------------------

const byLocale = new Map<string, { path: string; english: string }[]>();
for (const item of outstanding) {
  const list = byLocale.get(item.locale) ?? [];
  list.push({ path: item.path, english: item.english });
  byLocale.set(item.locale, list);
}

/** Groups by top-level namespace so a translator can be given one section. */
function namespaceOf(path: string): string {
  return path.split('.')[0] ?? 'other';
}

const perLocale = routing.locales.filter((locale) => locale !== routing.defaultLocale);
const first = byLocale.get(perLocale[0] as string) ?? [];

const lines: string[] = [
  '# Strings awaiting translation',
  '',
  '> Generated by `npm run build:messages`. Do not edit by hand — edit',
  '> `content/copy.ts` (English) or `messages/<locale>.json` (translations),',
  '> then regenerate.',
  '',
  '## What this is',
  '',
  'Every string below exists in English and does **not** exist in Arabic or',
  'Romanian. Nothing here has been machine translated, and nothing should be:',
  'this is a commercial document aimed at retail buyers and investors, and a',
  'machine translation of "we come back with a site assessment" is how a serious',
  'company reads as an unserious one.',
  '',
  '## How to work through it',
  '',
  '1. Open `messages/ar.json` or `messages/ro.json`.',
  '2. Find the key path from the table below.',
  '3. Replace the whole value — **including the `[[AR]]` / `[[RO]]` marker** —',
  '   with the translation.',
  '4. `npm run check:i18n` fails while any marker remains, so nothing',
  '   half-translated can reach production.',
  '',
  '## Notes for the translator',
  '',
  '- **Tone**: operational and precise, not marketing. We sell throughput,',
  '  uptime and material recovery. Prefer a concrete mechanism over an',
  '  adjective. Avoid sustainability boilerplate entirely.',
  '- **Audience order**: Egyptian retail chain decision makers first, investors',
  '  second. Where a phrase cannot serve both, serve the retailer.',
  '- **Do not translate**: routes (`/for-retailers`), fact ids, the legal',
  '  placeholder marker, or the company name.',
  '- **Numbers**: every figure on this site comes from `content/facts.ts` and is',
  '  not in these files. If a translation needs a number inline, flag it rather',
  '  than writing one.',
  '- **Arabic specifically**: the site mirrors to RTL automatically. Translations',
  '  do not need directional markers. Latin technical terms that stay Latin —',
  '  PET, RVM, m², ESG — should stay Latin.',
  '- **Legal strings** under `investorDisclaimer` and `dataRoomRequest.declaration`',
  '  are placeholders pending a lawyer in English too. Do not translate them yet.',
  '',
  `## Outstanding: ${first.length} strings per locale, ${outstanding.length} total`,
  '',
];

const namespaces = new Map<string, { path: string; english: string }[]>();
for (const item of first) {
  const namespace = namespaceOf(item.path);
  const list = namespaces.get(namespace) ?? [];
  list.push(item);
  namespaces.set(namespace, list);
}

for (const [namespace, items] of [...namespaces.entries()].sort()) {
  lines.push(`### \`${namespace}\` — ${items.length} strings`, '');
  lines.push('| Key | English |', '| --- | --- |');
  for (const item of items) {
    // Pipes and newlines would break the table.
    const english = item.english.replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(`| \`${item.path}\` | ${english} |`);
  }
  lines.push('');
}

writeFileSync(join(process.cwd(), 'content', 'i18n-todo.md'), `${lines.join('\n')}\n`, 'utf8');

console.log(
  `build-messages: wrote ${routing.locales.length} message files; ` +
    `${first.length} strings per locale awaiting translation.`,
);
